# Beispiel für die Guardian-Konfiguration (config.yaml)
# Diese Datei kann als Vorlage für die Policy genutzt werden.

timezone: "Europe/Berlin"
defaults:
  daily_quota_minutes: 90
  curfew:
    weekdays: "08:00-20:00"
    saturday: "08:00-22:00"
    sunday: "09:00-20:00"
  grace_minutes: 5
  bonus_pool_minutes: 0

users:
  kid1:
    daily_quota_minutes: 60
    curfew:
      weekdays: "07:30-19:30"
      saturday: "08:00-21:00"
      sunday: "09:00-19:00"
    bonus_pool_minutes: 15
  kid2:
    daily_quota_minutes: 90
    curfew:
      weekdays: "08:00-20:00"
      saturday: "08:00-22:00"
      sunday: "09:00-20:00"
    bonus_pool_minutes: 30

# Weitere Optionen können ergänzt werden:
# - allowlist: Liste erlaubter Programme/Apps
# - grace_minutes: Zeit nach Quota-Überschreitung
# - timezone: Zeitzone pro Nutzer
# - ...
