site_name: Guardian Docs
nav:
  - Home: index.md
  # - API:
  #     - guardian_daemon: reference/guardian_daemon.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            docstring_style: google
            merge_init_into_class: true
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
