pre-commit:
  parallel: true
  jobs:
    - name: daemon ruff
      glob: "guardian_daemon/**/*.py"
      run: uv run --package guardian_daemon ruff check --fix {staged_files}
      stage_fixed: true
    - name: daemon black
      glob: "guardian_daemon/**/*.py"
      run: uv run --package guardian_daemon black {staged_files}
      stage_fixed: true
    - name: daemon mypy
      glob: "guardian_daemon/**/*.py"
      run: pushd guardian_daemon ; uv run --active mypy --install-types --explicit-package-bases . ; popd
    - name: daemon isort
      glob: "guardian_daemon/**/*.py"
      run: uv run --package guardian_daemon isort {staged_files}
      stage_fixed: true
    - name: ctl ruff
      glob: "guardianctl/**/*.py"
      run: uv run --package guardianctl ruff check --fix {staged_files}
      stage_fixed: true
    - name: ctl black
      glob: "guardianctl/**/*.py"
      run: uv run --package guardianctl black {staged_files}
      stage_fixed: true
    - name: ctl mypy
      glob: "guardianctl/**/*.py"
      run: pushd guardianctl ; uv run --active mypy --install-types --explicit-package-bases . ; popd
    - name: ctl isort
      glob: "guardianctl/**/*.py"
      run: uv run --package guardianctl isort {staged_files}
      stage_fixed: true
    - name: agent ruff
      glob: "guardian_agent/**/*.py"
      run: uv run --package guardian_agent ruff check --fix {staged_files}
      stage_fixed: true
    - name: agent black
      glob: "guardian_agent/**/*.py"
      run: uv run --package guardian_agent black {staged_files}
      stage_fixed: true
    - name: agent mypy
      glob: "guardian_agent/**/*.py"
      run: pushd guardian_agent ; uv run --active mypy --install-types --explicit-package-bases . ; popd
    - name: agent isort
      glob: "guardian_agent/**/*.py"
      run: uv run --package guardian_agent isort {staged_files}
      stage_fixed: true
    - name: hub ruff
      glob: "guardian_hub/**/*.py"
      run: uv run --package guardian_hub ruff check --fix {staged_files}
      stage_fixed: true
    - name: hub black
      glob: "guardian_hub/**/*.py"
      run: uv run --package guardian_hub black {staged_files}
      stage_fixed: true
    - name: hub mypy
      glob: "guardian_hub/**/*.py"
      run: pushd guardian_hub ; uv run --active mypy --install-types --explicit-package-bases . ; popd
    - name: hub isort
      glob: "guardian_hub/**/*.py"
      run: uv run --package guardian_hub isort {staged_files}
      stage_fixed: true
    - name: markdownlint
      glob: "*.md"
      run: markdownlint-cli2 --fix {staged_files}
      stage_fixed: true
